version: "3"

services:
  database:
    container_name: wordlist
    image: postgres:alpine3.19
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=wordlist
    ports:
      - 9090:5432
    expose:
      - 9090
    volumes:
      - './database:/var/lib/postgresql/data/'

  test-database:
    container_name: wordlist-test
    image: postgres:alpine3.19
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=wordlist
    ports:
      - 9191:5432
    expose:
      - 9191


volumes:
  database:
