import Head from 'next/head';
import { StyledMain } from '../styles/styledMain';

const Home = () => {
	return (
		<>
			<Head>
				<title>WordList</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<StyledMain>
				<h1>WordList</h1>
				<p className='para'>Um site para memorizar palavras</p>

				<div className='menu'>
					<button>Login</button>
					<button>Criar Conta</button>
				</div>
			</StyledMain>
		</>
	);
};

export default Home;
